const DESCRIPTION_MULTIPLE_CHOICE = 0;
const DESCRIPTION_UNIQUE_CHOISE = 1;
const COMPLETE_MULTIPLE_CHOISE = 2;
const COMPLETE_UNIQUE_CHOISE = 3;
const SORT_PHRASES_DIALOGUE = 4;
const SORT_WORDS_PHRASE = 5;
const SORT_LETTERS_WORD = 6;
const AUDIO = 7;
